### ISSUE TITLE
Unable to execute typo3-rector 

### ISSUE THREAD

**Issue by utrotzek** [sabbelasichon/typo3-rector#1326]
Currently it is not possible to execute the rector sets defined in this package. When executing

```bash
bin/rector process
```
the execution stops with the following error message:

```
[ERROR] The configuration key "TYPO3\CMS\Backend\Controller\Page\LocalizationController" is unsupported for definition
         "Rector\Renaming\Rector\MethodCall\RenameMethodCallRector" in
         "/app/vendor/ssch/typo3-rector/config/typo3-93.yaml". Allowed configuration keys are "alias", "parent",
         "class", "shared", "synthetic", "lazy", "public", "abstract", "deprecated", "factory", "file", "arguments",
         "properties", "configurator", "calls", "tags", "decorates", "decoration_inner_name", "decoration_priority",
         "decoration_on_invalid", "autowire", "autoconfigure", "bind" in
         /app/vendor/ssch/typo3-rector/config/typo3-93.yaml (which is being imported from "/app/rector.yaml")
```

I've used the following configuration for example. But the error occured with any other configuration i used as well.

**composer.json**
```json
   "require-dev": {
        "rector/rector": "dev-master",
        "ssch/typo3-rector": "dev-master"
    },
```

**Rector.yml**
```yaml
imports:
  - { resource: 'vendor/ssch/typo3-rector/config/typo3-93.yaml' }
parameters:
  sets:
    - 'php71'
    - 'php72'
    - 'php73'
    - 'php74'
```
