### ISSUE TITLE
Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers() must be of the type int, null given,

### ISSUE THREAD

**Issue by robsonrobi** [sabbelasichon/typo3-rector#1462]
Using TYPO3 9 (just upgrading to it) with php 7.3 i get in every viewhelper or command the error:

Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers() must be of the type int, null given

```
parameters:
  # FQN classes are not imported by default. If you don't to do do it manually after every Rector run, enable it by:
  auto_import_names: false
  # this will not import root namespace classes, like \DateTime or \Exception
  import_short_classes: false
  # this will not import classes used in PHP DocBlocks, like in /** @var \Some\Class */
  import_doc_blocks: false
  php_version_features: '73'

imports:
  - { resource: 'vendor/ssch/typo3-rector/config/services.yaml' }

services:
  Ssch\TYPO3Rector\Rector\Fluid\ViewHelpers\MoveRenderArgumentsToInitializeArgumentsMethodRector: ~
```

Any Idea
