### ISSUE TITLE
Documentation about usage of Docker Image

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1920]

**Comment by PhilippKuhlmay** [comment]
This is my configuration for my GitLab Pipeline. At the moment I use all of the 3 images, Version 0.8.9, dev-master and latest. I am doing this for testing only. A shorter pipeline would be, if I only use one of the tags, not all.
```
stages:
  - rector

.rector:
  stage: rector
  image: schreiberten/typo3-rector
  only:
    - pushes
  except:
    refs:
      - develop
  script:
    - typo3-rector process . --dry-run

rector-latest:
  extends: .rector
  image: schreiberten/typo3-rector:latest

rector-master:
  extends: .rector
  image: schreiberten/typo3-rector:dev-master

rector-089:
  extends: .rector
  image: schreiberten/typo3-rector:0.8.9
```
