### ISSUE TITLE
Suggestion for EXT:form language configuration

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2437]
In v10 the registration of locallang files for EXT:form frontend changed from old:
```
TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                translation:
                  translationFile:
                    10: 'EXT:form/Resources/Private/Language/locallang.xlf'
                    20: 'EXT:myextension/Resources/Private/Language/locallang.xlf'
```

```
TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                translation:
                  translationFiles:
                    20: 'EXT:myextension/Resources/Private/Language/locallang.xlf'
```

I think is should definitely be a rector rule?
