### ISSUE TITLE
EmailFinisherRector does not update properties in variants

### ISSUE THREAD

**Issue by koehnlein** [sabbelasichon/typo3-rector#2561]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.52             |

The EmailFinisherRector #1263 does not update finisher properties, nested in variants.

## Expected Behaviour

The old YAML file looks like this:

```yaml
variants:
  -
    identifier: variant-1
    condition: 'formValues["foo"] == "bar"'
    finishers:
      -
        identifier: EmailToReceiver
        options:
          subject: 'Example Subject'
          recipientAddress: user@example.org
          recipientName: 'Example Recipient'
          senderAddress: no-reply@example.org
          senderName: '{text-2} {text-1}'
          replyToAddress: '{email}'
```

This example block keeps untouched, but should be converted into:

```yaml
variants:
  -
    identifier: variant-1
    condition: 'formValues["foo"] == "bar"'
    finishers:
      -
        identifier: EmailToReceiver
        options:
          subject: 'Example Subject'
          recipients:
            user@example.org: 'Example Recipient'
          senderAddress: no-reply@example.org
          senderName: '{text-2} {text-1}'
          replyToRecipients: 
            - '{email}'
```
