### ISSUE TITLE
Important: #101567 - Use Symfony attribute to autoconfigure cli commands

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3911]
Important: #101567 - Use Symfony attribute to autoconfigure cli commands

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4.x/Important-101567-UseSymfonyAttributeToAutoconfigureCliCommands.html

---
title: "Important: #101567 - Use Symfony attribute to autoconfigure cli
  commands"
---

See [101567](https://forge.typo3.org/issues/101567)

# Description

The symfony PHP attribute
`\Symfony\Component\Console\Attribute\AsCommand` is now accepted to
register console commands. This way CLI commands can be registered by
setting the attribute on the command class. Only the parameters command,
description are still viable. In order to overwrite the parameters
schedulable and hidden use the old `Services.yaml` way to register
console commands. By default schedulable is true and hidden is false.

Before:

``` yaml
MyVendor\MyExtension\Command\MyCommand:
  tags:
    - name: 'console.command'
      command: 'myprefix:dofoo'
      description: 'My description'
      schedulable: true
      hidden: false
```

After:

The registration can be removed from the `Services.yaml` file and the
attribute is assigned to the command class instead:

``` php
<?php

namespace MyVendor\MyExtension\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Attribute\AsCommand;

#[AsCommand(name: 'myprefix:dofoo', description: 'My description')]
class MyCommand extends Command
{
}
```

# Impact

The registration of cli commands is simplified that way. When using this
attribute there is no need to register the command in the
`Services.yaml` file. Existing configurations work as before.

<div class="index">

Backend, CLI, PHP-API, ext:core

</div>
