### ISSUE TITLE
Important: #102507 - Default CKEditor5 allowed classes and data attributes configurated reverted

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3976]
Important: #102507 - Default CKEditor5 allowed classes and data attributes configurated reverted

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4.x/Important-102507-DefaultCKEditor5AllowedClassesAndDataAttributesConfiguratedReverted.html

---
title: "Important: #102507 - Default CKEditor5 allowed classes and data
  attributes configurated reverted"
---

See [102507](https://forge.typo3.org/issues/102507)

# Description

With TYPO3 v12.4.7 (see `99738`) an option to allow all classes in
CKEditor5 has been enabled in the TYPO3 default configuration which
implicitly caused all custom html elements to be allowed. This rule has
now been dropped from the default configuration:

``` yaml
htmlSupport:
  allow:
    - { classes: true, attributes: { pattern: 'data-.+' } }
```

The configuration matched to any HTML element available in the CKEditor5
General HTML Support (GHS) schema definition. This became an issue,
since CKEditor5 relies on the set of allowed elements and classes when
processing content that is pasted from Microsoft Office.

Installations that relied on the fact that v12.4.7 allowed all CSS
classes in CKEditor5 should encode the set of available style
definitions via <span
class="title-ref">editor.config.style.definitions</span> which will make
them accessible to editors via the style dropdown toolbar element:

``` yaml
style:
  definitions:
     - { name: "Descriptive Label", element: "p", classes: ['my-class'] }
```

Custom data attributes can be allowed via General HTML Support:

``` yaml
htmlSupport:
  allow:
    - { name: 'div', attributes: ['data-foobar'] }
```

<div class="index">

RTE, YAML, ext:rte_ckeditor

</div>
