### ISSUE TITLE
Important: #100847 - Added font plugin to CKEditor5

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#4250]
Important: #100847 - Added font plugin to CKEditor5

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4.x/Important-100847-AddedFontPluginToCKEditor5.html

# Important: \#100847 - Added font plugin to CKEditor5

See [100847](https://forge.typo3.org/issues/100847)

## Description

The font plugin has been added to the CKEditor5. In order to use the
font plugin, the RTE configuration needs to be adapted:

``` yaml
editor:
  config:
    toolbar:
      items:
        # add button to select font family
        - fontFamily
        # add button to select font size
        - fontSize
        # add button to select font color
        - fontColor
        # add button to select font background color
        - fontBackgroundColor

    fontColor:
      colors:
        - { label: 'Orange', color: '#ff8700' }
        - { label: 'Blue', color: '#0080c9' }
        - { label: 'Green', color: '#209d44' }

    fontBackgroundColor:
      colors:
        - { label: 'Stage orange light', color: '#fab85c' }

    fontFamily:
      options:
        - 'default'
        - 'Arial, sans-serif'

    fontSize:
      options:
        - 'default'
        - 18
        - 21

    importModules:
      - { 'module': '@ckeditor/ckeditor5-font', 'exports': ['Font'] }
```

More information can be found in the official
[documentation](https://ckeditor.com/docs/ckeditor5/latest/features/font.html).

<div class="index">

RTE, ext:rte_ckeditor

</div>
