### ISSUE TITLE
Important: #103392 - Form framework select markup changed

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#4252]
Important: #103392 - Form framework select markup changed

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4.x/Important-103117-FormFrameworkSelectMarkupChanged.html

# Important: \#103392 - Form framework select markup changed

See [103392](https://forge.typo3.org/issues/103392)

## Description

With [103117](https://forge.typo3.org/issues/103117), the <span class="title-ref">elementClassAttribute</span>
of the "SingleSelect", "CountrySelect" and "MultiSelect" fields got
changed from <span class="title-ref">form-control</span> to
<span class="title-ref">form-select</span> in EXT:form, as defined by
[Bootstrap](https://getbootstrap.com/docs/5.3/forms/select/), if the
Bootstrap 5 markup (`templateVariant: version2`) is used.

If needed, the old markup can be restored by overriding the
configuration as follows:

``` yaml
prototypes:
  standard:
    formElementsDefinition:
      CountrySelect:
        variants:
          -
            identifier: template-variant
            properties:
              elementClassAttribute: form-control
      MultiSelect:
        variants:
          -
            identifier: template-variant
            properties:
              elementClassAttribute: form-control
      SingleSelect:
        variants:
          -
            identifier: template-variant
            properties:
              elementClassAttribute: form-control
```

<div class="index">

Frontend, ext:form

</div>
