### ISSUE TITLE
Breaking: #85323 - Move GET parameters in sitemap into namespace

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#4516]
Breaking: #85323 - Move GET parameters in sitemap into namespace

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/14.0/Breaking-85323-SeoParameterNamespace.html

# Breaking: \#85323 - Move GET parameters in sitemap into namespace

See [85323](https://forge.typo3.org/issues/85323)

## Description

The names of the GET parameters used in the sitemap generated by EXT:seo
have been changed from <span class="title-ref">page</span> and
<span class="title-ref">sitemap</span> to
<span class="title-ref">tx_seo\[page\]</span> and
<span class="title-ref">tx_seo\[sitemap\]</span> respectively.

## Impact

Applications, routing configuration and 3rd party tools that rely on the
parameters being named <span class="title-ref">page</span> and
<span class="title-ref">sitemap</span> break.

## Affected installations

This affects installations, which use the arguments
<span class="title-ref">page</span> and
<span class="title-ref">sitemap</span> or override the sitemap templates
of EXT:seo.

## Migration

In case the arguments are mapped in the routing configuration, the code
needs to be slightly adopted. A working example issue

``` yaml
routeEnhancers:
  Sitemap:
    type: Simple
    routePath: 'sitemap-type/{sitemap}'
    aspects:
      sitemap:
        type: StaticValueMapper
        map:
          pages: pages
          tx_news: tx_news
          my_other_sitemap: my_other_sitemap
    _arguments:
      sitemap: 'tx_seo/sitemap'
```

If the templates of
<span class="title-ref">EXT:seo/Resources/Private/Templates/XmlSitemap/Index.xml</span>
have been modified, adopt the generated links to fit the original ones.

In case the URL to a single sitemap has been provided to a 3rd party
tool like a crawler, search engine, ... it must be added again with the
new URL.

<div class="index">

Frontend, ext:seo, NotScanned

</div>
